version: '3.3'
services:
  ### MySQL Container
  mysql:
    image: mysql:latest
    container_name: mysql
#    restart: on-failure
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./privilegies.sql:/docker-entrypoint-initdb.d/privilegies.sql